Lint/RescueException:
  Exclude:
    - 'Rakefile'
    - 'libraries/helpers.rb'

Naming/AccessorMethodName:
  Exclude:
    - 'Rakefile'
    - 'libraries/helpers.rb'

Style/RescueModifier:
  Exclude:
    - 'Rakefile'
    - 'libraries/helpers.rb'

Style/GuardClause:
  Enabled: false
  Exclude:
    - 'Rakefile'
    - 'libraries/helpers.rb'

Style/IfUnlessModifier:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

# Longer classes are okay.
Metrics/ClassLength:
  Max: 200
Metrics/MethodLength:
  Max: 30
Metrics/ModuleLength:
  Max: 150
Metrics/BlockLength:
  Max: 150

# Not on VT100s anymore.
Layout/LineLength:
  Max: 180

# We're not against complexity.
Metrics/AbcSize:
  Max: 55
Metrics/CyclomaticComplexity:
  Max: 20
Metrics/PerceivedComplexity:
  Max: 20

# Mixlib::ShellOut is nice to have as an older hash syntax
Style/HashSyntax:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/WordArray:
  Enabled: False

# Cookstyle specific things
ChefStyle/CommentFormat:
  Enabled: False # we are not Chef

ChefModernize/WhyRunSupportedTrue:
  Enabled: False # we are still supporting v12

ChefModernize/RespondToInMetadata:
  Enabled: False # we're supporting 12.5 still

ChefModernize/DefinesChefSpecMatchers:
  Enabled: False # we haven't moved to newer ChefSpec yet
